CREATE TABLE IF NOT EXISTS masters (
    id SERIAL PRIMARY KEY,
    master_type VARCHAR(50) NOT NULL,
    value VARCHAR(100) NOT NULL,
    label VARCHAR(200) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    UNIQUE(master_type, value)
);

INSERT INTO masters (master_type, value, label, sort_order) VALUES
  ('category','consumer','コンシューマ',0),
  ('category','arcade','アーケード',1),
  ('category','hardware','ハード',2),
  ('category','other','その他',3),
  ('hardware','AC','アーケード基板 (AC)',0),
  ('hardware','PS5','PlayStation 5',1),
  ('hardware','PS4','PlayStation 4',2),
  ('hardware','PS3','PlayStation 3',3),
  ('hardware','PS2','PlayStation 2',4),
  ('hardware','PS1','PlayStation',5),
  ('hardware','switch2','Nintendo Switch 2',6),
  ('hardware','switch1','Nintendo Switch',7),
  ('hardware','WiiU','Wii U',8),
  ('hardware','Wii','Wii',9),
  ('hardware','gamecube','ゲームキューブ',10),
  ('hardware','N64','NINTENDO 64',11),
  ('hardware','SFC','スーパーファミコン',12),
  ('hardware','FC','ファミコン',13),
  ('hardware','DC','ドリームキャスト',14),
  ('hardware','SS','セガサターン',15),
  ('hardware','DS','ニンテンドーDS',16),
  ('hardware','GBA','ゲームボーイアドバンス',17),
  ('hardware','GBC','ゲームボーイカラー',18),
  ('hardware','GB','ゲームボーイ',19),
  ('genre','action','アクション',0),
  ('genre','rpg','RPG',1),
  ('genre','shooting','シューティング',2),
  ('genre','fighting','格闘',3),
  ('genre','puzzle','パズル',4),
  ('genre','sports','スポーツ',5),
  ('genre','racing','レース',6),
  ('genre','adventure','アドベンチャー',7),
  ('genre','simulation','シミュレーション',8),
  ('genre','strategy','ストラテジー',9),
  ('genre','horror','ホラー',10),
  ('genre','other','その他',11),
  ('edition','standard','通常版',0),
  ('edition','first_print','初回限定版',1),
  ('edition','limited','限定版',2),
  ('edition','deluxe','デラックス版',3),
  ('edition','collectors','コレクターズエディション',4),
  ('edition','budget','廉価版',5),
  ('edition','other','その他',6)
ON CONFLICT (master_type, value) DO NOTHING;
